/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author DHAFINDRA
 */
public class TambahAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TambahAdmin
     */
    public TambahAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        LabelTambahAdmin = new javax.swing.JLabel();
        BGDataAdmin = new javax.swing.JPanel();
        LabelDataAdmin = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelAlamat = new javax.swing.JLabel();
        LabelnoTelp = new javax.swing.JLabel();
        TextFieldAlamat = new javax.swing.JTextField();
        TextFieldNama = new javax.swing.JTextField();
        TextFieldnoTelp = new javax.swing.JTextField();
        LabelKelamin = new javax.swing.JLabel();
        buttonCowo = new javax.swing.JRadioButton();
        buttonCewe = new javax.swing.JRadioButton();
        LabelUsername = new javax.swing.JLabel();
        TextFieldUsername = new javax.swing.JTextField();
        LabelPassword = new javax.swing.JLabel();
        TextFieldPassword = new javax.swing.JTextField();
        buttonSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(0, 0, 0));

        LabelTambahAdmin.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        LabelTambahAdmin.setText("Tambah Admin");

        BGDataAdmin.setBackground(new java.awt.Color(23, 23, 23));

        LabelDataAdmin.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LabelDataAdmin.setText("Data Admin");

        LabelNama.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelNama.setText("Nama");

        LabelAlamat.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelAlamat.setText("Alamat");

        LabelnoTelp.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelnoTelp.setText("no. Telp");

        TextFieldAlamat.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAlamatActionPerformed(evt);
            }
        });

        TextFieldNama.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNamaActionPerformed(evt);
            }
        });

        TextFieldnoTelp.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldnoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnoTelpActionPerformed(evt);
            }
        });

        LabelKelamin.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelKelamin.setText("Jenis Kelamin");

        buttonCowo.setBackground(new java.awt.Color(23, 23, 23));
        buttonCowo.setText("Laki-Laki");

        buttonCewe.setBackground(new java.awt.Color(23, 23, 23));
        buttonCewe.setText("Perempuan");

        LabelUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelUsername.setText("Username");

        TextFieldUsername.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldUsernameActionPerformed(evt);
            }
        });

        LabelPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelPassword.setText("Password");

        TextFieldPassword.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPasswordActionPerformed(evt);
            }
        });

        buttonSimpan.setBackground(new java.awt.Color(48, 48, 48));
        buttonSimpan.setText("Simpan");
        buttonSimpan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout BGDataAdminLayout = new javax.swing.GroupLayout(BGDataAdmin);
        BGDataAdmin.setLayout(BGDataAdminLayout);
        BGDataAdminLayout.setHorizontalGroup(
            BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGDataAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BGDataAdminLayout.createSequentialGroup()
                        .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BGDataAdminLayout.createSequentialGroup()
                                .addComponent(LabelNama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BGDataAdminLayout.createSequentialGroup()
                                .addComponent(LabelAlamat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(BGDataAdminLayout.createSequentialGroup()
                                .addComponent(LabelnoTelp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TextFieldnoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelDataAdmin)
                            .addGroup(BGDataAdminLayout.createSequentialGroup()
                                .addComponent(LabelKelamin)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCowo)
                                .addGap(18, 18, 18)
                                .addComponent(buttonCewe)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BGDataAdminLayout.createSequentialGroup()
                        .addComponent(LabelUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BGDataAdminLayout.createSequentialGroup()
                        .addComponent(LabelPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(BGDataAdminLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(buttonSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BGDataAdminLayout.setVerticalGroup(
            BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGDataAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDataAdmin)
                .addGap(18, 18, 18)
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(TextFieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAlamat)
                    .addComponent(TextFieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelnoTelp)
                    .addComponent(TextFieldnoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKelamin)
                    .addComponent(buttonCowo)
                    .addComponent(buttonCewe))
                .addGap(18, 18, 18)
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUsername)
                    .addComponent(TextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(BGDataAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPassword)
                    .addComponent(TextFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(BGDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(LabelTambahAdmin)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(LabelTambahAdmin)
                .addGap(18, 18, 18)
                .addComponent(BGDataAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAlamatActionPerformed

    private void TextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNamaActionPerformed

    private void TextFieldnoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnoTelpActionPerformed

    private void TextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldUsernameActionPerformed

    private void TextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGDataAdmin;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelDataAdmin;
    private javax.swing.JLabel LabelKelamin;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelPassword;
    private javax.swing.JLabel LabelTambahAdmin;
    private javax.swing.JLabel LabelUsername;
    private javax.swing.JLabel LabelnoTelp;
    private javax.swing.JTextField TextFieldAlamat;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldPassword;
    private javax.swing.JTextField TextFieldUsername;
    private javax.swing.JTextField TextFieldnoTelp;
    private javax.swing.JRadioButton buttonCewe;
    private javax.swing.JRadioButton buttonCowo;
    private javax.swing.JButton buttonSimpan;
    // End of variables declaration//GEN-END:variables
}
