/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author DHAFINDRA
 */
public class TambahPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form TambahPelanggan
     */
    public TambahPelanggan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LabelTambahDataPelanggan2 = new javax.swing.JLabel();
        LabelNama2 = new javax.swing.JLabel();
        LabelAlamat2 = new javax.swing.JLabel();
        LabelnoTelp2 = new javax.swing.JLabel();
        LabelKelamin2 = new javax.swing.JLabel();
        buttonCowo2 = new javax.swing.JRadioButton();
        buttonCewe2 = new javax.swing.JRadioButton();
        TextFieldnoTelp2 = new javax.swing.JTextField();
        TextFieldAlamat2 = new javax.swing.JTextField();
        TextFieldNama2 = new javax.swing.JTextField();
        buttonSimpan2 = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel4.setBackground(new java.awt.Color(23, 23, 23));

        LabelTambahDataPelanggan2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LabelTambahDataPelanggan2.setText("Tambah Data Pelanggan");

        LabelNama2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelNama2.setText("Nama");

        LabelAlamat2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelAlamat2.setText("Alamat");

        LabelnoTelp2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelnoTelp2.setText("no. Telp");

        LabelKelamin2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelKelamin2.setText("Jenis Kelamin");

        buttonCowo2.setBackground(new java.awt.Color(23, 23, 23));
        buttonCowo2.setText("Laki-Laki");

        buttonCewe2.setBackground(new java.awt.Color(23, 23, 23));
        buttonCewe2.setText("Perempuan");

        TextFieldnoTelp2.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldnoTelp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnoTelp2ActionPerformed(evt);
            }
        });

        TextFieldAlamat2.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldAlamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldAlamat2ActionPerformed(evt);
            }
        });

        TextFieldNama2.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldNama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNama2ActionPerformed(evt);
            }
        });

        buttonSimpan2.setBackground(new java.awt.Color(48, 48, 48));
        buttonSimpan2.setText("Simpan");
        buttonSimpan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonKembali.setBackground(new java.awt.Color(48, 48, 48));
        buttonKembali.setText("Kembali");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNama2)
                            .addComponent(LabelAlamat2)
                            .addComponent(LabelnoTelp2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldNama2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(TextFieldnoTelp2)
                            .addComponent(TextFieldAlamat2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelTambahDataPelanggan2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(LabelKelamin2)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonCowo2)
                                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonCewe2))))
                        .addGap(0, 82, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTambahDataPelanggan2)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNama2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAlamat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAlamat2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldnoTelp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelnoTelp2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKelamin2)
                    .addComponent(buttonCowo2)
                    .addComponent(buttonCewe2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldnoTelp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnoTelp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnoTelp2ActionPerformed

    private void TextFieldAlamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldAlamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldAlamat2ActionPerformed

    private void TextFieldNama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNama2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNama2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAlamat;
    private javax.swing.JLabel LabelAlamat1;
    private javax.swing.JLabel LabelAlamat2;
    private javax.swing.JLabel LabelKelamin;
    private javax.swing.JLabel LabelKelamin1;
    private javax.swing.JLabel LabelKelamin2;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNama1;
    private javax.swing.JLabel LabelNama2;
    private javax.swing.JLabel LabelTambahDataPelanggan;
    private javax.swing.JLabel LabelTambahDataPelanggan1;
    private javax.swing.JLabel LabelTambahDataPelanggan2;
    private javax.swing.JLabel LabelnoTelp;
    private javax.swing.JLabel LabelnoTelp1;
    private javax.swing.JLabel LabelnoTelp2;
    private javax.swing.JTextField TextFieldAlamat;
    private javax.swing.JTextField TextFieldAlamat1;
    private javax.swing.JTextField TextFieldAlamat2;
    private javax.swing.JTextField TextFieldNama;
    private javax.swing.JTextField TextFieldNama1;
    private javax.swing.JTextField TextFieldNama2;
    private javax.swing.JTextField TextFieldnoTelp;
    private javax.swing.JTextField TextFieldnoTelp1;
    private javax.swing.JTextField TextFieldnoTelp2;
    private javax.swing.JRadioButton buttonCewe;
    private javax.swing.JRadioButton buttonCewe1;
    private javax.swing.JRadioButton buttonCewe2;
    private javax.swing.JRadioButton buttonCowo;
    private javax.swing.JRadioButton buttonCowo1;
    private javax.swing.JRadioButton buttonCowo2;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonSimpan;
    private javax.swing.JButton buttonSimpan1;
    private javax.swing.JButton buttonSimpan2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
