/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author DHAFINDRA
 */
public class TambahTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form TambahTransaksi
     */
    public TambahTransaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        LabelTambahDataTransaksi = new javax.swing.JLabel();
        LabelIDPelanggan1 = new javax.swing.JLabel();
        TextFieldIDPelanggan1 = new javax.swing.JTextField();
        LabelJenisLayanan = new javax.swing.JLabel();
        ComboBoxLayanan = new javax.swing.JComboBox<>();
        LabelStatus = new javax.swing.JLabel();
        ComboBoxStatus = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        LabelTgl = new javax.swing.JLabel();
        LabelJenisLayanan2 = new javax.swing.JLabel();
        LabelJenisLayanan3 = new javax.swing.JLabel();
        TextFieldIDPelanggan2 = new javax.swing.JTextField();
        TextFieldIDPelanggan3 = new javax.swing.JTextField();
        TextFieldIDPelanggan4 = new javax.swing.JTextField();
        buttonHitungTotal = new javax.swing.JButton();
        buttonTambahItem = new javax.swing.JButton();
        buttonSimpan2 = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(23, 23, 23));

        LabelTambahDataTransaksi.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        LabelTambahDataTransaksi.setText("Tambah Data Transaksi");

        LabelIDPelanggan1.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelIDPelanggan1.setText("ID Pelanggan");

        TextFieldIDPelanggan1.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldIDPelanggan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDPelanggan1ActionPerformed(evt);
            }
        });

        LabelJenisLayanan.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan.setText("Jenis Layanan");

        ComboBoxLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Item 2", "Item 3", "Item 4" }));
        ComboBoxLayanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLayananActionPerformed(evt);
            }
        });

        LabelStatus.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelStatus.setText("Status Pencucian");

        ComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Selesai", "Selesai" }));
        ComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxStatusActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        LabelTgl.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelTgl.setText("Tanggal Pemasukkan");

        LabelJenisLayanan2.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan2.setText("Item");

        LabelJenisLayanan3.setFont(new java.awt.Font("Yu Gothic UI", 0, 11)); // NOI18N
        LabelJenisLayanan3.setText("Total");

        TextFieldIDPelanggan2.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldIDPelanggan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDPelanggan2ActionPerformed(evt);
            }
        });

        TextFieldIDPelanggan3.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldIDPelanggan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDPelanggan3ActionPerformed(evt);
            }
        });

        TextFieldIDPelanggan4.setBackground(new java.awt.Color(0, 0, 0));
        TextFieldIDPelanggan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDPelanggan4ActionPerformed(evt);
            }
        });

        buttonHitungTotal.setBackground(new java.awt.Color(48, 48, 48));
        buttonHitungTotal.setText("Hitung");
        buttonHitungTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonTambahItem.setBackground(new java.awt.Color(48, 48, 48));
        buttonTambahItem.setText("Tambah");
        buttonTambahItem.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonSimpan2.setBackground(new java.awt.Color(48, 48, 48));
        buttonSimpan2.setText("Simpan");
        buttonSimpan2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonKembali.setBackground(new java.awt.Color(48, 48, 48));
        buttonKembali.setText("Kembali");
        buttonKembali.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelIDPelanggan1)
                    .addComponent(LabelJenisLayanan)
                    .addComponent(LabelTambahDataTransaksi)
                    .addComponent(LabelStatus))
                .addGap(1, 1, 1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboBoxStatus, 0, 102, Short.MAX_VALUE)
                    .addComponent(ComboBoxLayanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldIDPelanggan1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTgl)
                    .addComponent(LabelJenisLayanan2)
                    .addComponent(LabelJenisLayanan3))
                .addGap(41, 41, 41)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(TextFieldIDPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(TextFieldIDPelanggan3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonTambahItem, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(TextFieldIDPelanggan4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonHitungTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldIDPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTgl))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJenisLayanan2)
                    .addComponent(TextFieldIDPelanggan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTambahItem))
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJenisLayanan3)
                    .addComponent(TextFieldIDPelanggan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonHitungTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTambahDataTransaksi)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldIDPelanggan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelIDPelanggan1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJenisLayanan)
                            .addComponent(ComboBoxLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelStatus)
                            .addComponent(ComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldIDPelanggan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDPelanggan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDPelanggan1ActionPerformed

    private void ComboBoxLayananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLayananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxLayananActionPerformed

    private void ComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxStatusActionPerformed

    private void TextFieldIDPelanggan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDPelanggan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDPelanggan2ActionPerformed

    private void TextFieldIDPelanggan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDPelanggan3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDPelanggan3ActionPerformed

    private void TextFieldIDPelanggan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDPelanggan4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDPelanggan4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxLayanan;
    private javax.swing.JComboBox<String> ComboBoxStatus;
    private javax.swing.JLabel LabelIDPelanggan1;
    private javax.swing.JLabel LabelJenisLayanan;
    private javax.swing.JLabel LabelJenisLayanan2;
    private javax.swing.JLabel LabelJenisLayanan3;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelTambahDataTransaksi;
    private javax.swing.JLabel LabelTgl;
    private javax.swing.JTextField TextFieldIDPelanggan1;
    private javax.swing.JTextField TextFieldIDPelanggan2;
    private javax.swing.JTextField TextFieldIDPelanggan3;
    private javax.swing.JTextField TextFieldIDPelanggan4;
    private javax.swing.JButton buttonHitungTotal;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonSimpan2;
    private javax.swing.JButton buttonTambahItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
